######### Light Automations ##########

# This will turn the living room lights on when we open the door (presumably arriving home)
- alias: Lights Front Door Trigger
  initial_state: True
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.living_room_door_status
    from: 'closed'
    to: 'open'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.lr_light_slaves
      state: 'off'
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.dark_sky_cloud_coverage
          above: 60
        - condition: sun
          after: sunset
          after_offset: "-4:00:00"
  action:
    service: light.turn_on
    entity_id: group.lr_light_slaves
    data:
      brightness: 255

# This will turn the living room lights on and dim them after 830 when we open the door (presumably arriving home)
- alias: Lights Front Door Trigger Late (8:30pm)
  initial_state: True
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.living_room_door_status
    from: 'closed'
    to: 'open'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '20:30:00'
      before: '01:00:00'
    - condition: state
      entity_id: group.lr_light_slaves
      state: 'off'
  action:
    service: light.turn_on
    entity_id: group.lr_light_slaves
    data:
      brightness: 5

# This will turn on the front house lights 1 hour before sunset
- alias: Lights Front House Sunset On
  initial_state: True
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: light.turn_on
    entity_id: group.front_light_slaves
    data:
      brightness: 255

# This will turn the front house lights on when we arrive home
- alias: Lights Front Arrival
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: device_tracker.android317bb99286d305e1, device_tracker.android9190877cf1e0284f
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.front_light_slaves
      state: 'off'
    - condition: sun
      after: sunset
      after_offset: "-1:00:00"
  action:
    service: light.turn_on
    entity_id: group.front_light_slaves
    data:
      brightness: 255

# This will turn the front house lights off after 15 minutes if they come on after 11pm
- alias: Light Front House off after 15m after 11pm
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: group.front_light_slaves
    to: 'on'
    for:
      minutes: 15
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.front_light_slaves
        state: 'on'
      - condition: time
        after: '23:00:10'
  action:
    service: light.turn_off
    entity_id: group.front_light_slaves

# This will turn off the front house lights at 11pm
- alias: Lights Front House 11pm Off
  initial_state: True
  hide_entity: true
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: light.turn_off
    entity_id: group.front_light_slaves


######### Alarm Automations ##########
- alias: Alarm Away
  initial_state: True
  hide_entity: true
  trigger:
  - platform: state
    entity_id: sensor.living_room_door_status
    from: 'closed'
    to: 'open'
  - platform: state
    entity_id: sensor.deck_door_status
    from: 'closed'
    to: 'open'
  - platform: state
    entity_id: sensor.basement_office_door_status
    from: 'closed'
    to: 'open'
  - platform: state
    entity_id: sensor.sunken_room_door_alarm_level
    from: 'closed'
    to: 'open'
  - platform: state
    entity_id: sensor.family_room_door_alarm_level
    from: 'closed'
    to: 'open'
  condition:
    condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.ha_alarm

#### Flash the lights
- alias: Triggered Flash
  hide_entity: true
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    from: 'armed_away'
    to: 'triggered'
  action:
  #- service: script.turn_on
  #  entity_id: script.light_flash

### Trigger Pushover
- alias: Triggered Pushover
  initial_state: true
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: 'triggered'
  action:
  - service: notify.frank_pushover
    data:
      message: 'Home Alarm Triggered {{ now().strftime("%Y-%m-%d %-I:%m:%S %p") }}'

#### Alarm disarmed, switch to normal
- alias: Disarmed Off
  hide_entity: true
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    from: 'triggered'
    to: 'disarmed'
  action:
    - service: script.turn_off
      entity_id: script.light_loop
    - service: script.turn_off
      entity_id: script.light_flash
    - service: script.turn_off
      entity_id: script.light_loop
    - service: script.turn_off
      entity_id: script.light_flash
    - service: notify.frank_pushover
      data:
        message: 'Home Alarm Reset {{ now().strftime("%Y-%m-%d %-I:%m:%S %p") }}'

#- alias: Test Pushover
#  hide_entity: true
#  trigger:
#    platform: state
#    entity_id: alarm_control_panel.ha_alarm
#    state: 'disarmed'
#  action:
#    - service: notify.frank_pushover
#      data:
#        message: 'Home Alarm Reset {{ now().strftime("%Y-%m-%d %-I:%m:%S %p") }}'


- id: roku_lr_light_on
  alias: Use Roku to Turn on LR Lights
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Fake Roku
      type: keypress
      key: Info
  action:
    service: light.turn_on
    entity_id: group.lr_light_slaves

- id: roku_lr_light_off
  alias: Use Roku to Turn off LR Lights
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Fake Roku
      type: keypress
      key: Rev
  action:
    service: light.turn_off
    entity_id: group.lr_light_slaves

- id: roku_lr_light_up
  alias: Use Roku to Turn up LR Lights
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Fake Roku
      type: keypress
      key: OK
  action:
    service: light.turn_on
    entity_id: group.lr_light_slaves
    data_template:
      brightness: >
        {% if state_attr('light.living_room_floor_lamps', 'brightness') is defined %}
          {{ state_attr('light.living_room_floor_lamps', 'brightness') + 50 }}
        {% else %}
          50
        {%endif %}

- id: roku_lr_light_50
  alias: Use Roku to Turn LR Lights to 50%
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Fake Roku
      type: keypress
      key: Back
  action:
    service: light.turn_on
    entity_id: group.lr_light_slaves
    data:
      brightness: 90

- id: roku_lr_light_down
  alias: Use Roku to Turn down LR Lights
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Fake Roku
      type: keypress
      key: InstantReplay
  action:
    service: light.turn_on
    entity_id: group.lr_light_slaves
    data_template:
      brightness: >
        {% if state_attr('light.living_room_floor_lamps', 'brightness') is defined %}
          {{ state_attr('light.living_room_floor_lamps', 'brightness') - 50 }}
        {%endif %}

- id: roku_lr_light_down_max
  alias: Use Roku to Turn down LR Lights to lowest
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Fake Roku
      type: keypress
      key: Search
  action:
    service: light.turn_on
    entity_id: group.lr_light_slaves
    data:
      brightness: 1

- !include caseta/basement_pico_on.yaml
- !include caseta/basement_pico_off.yaml
- !include caseta/basement_on.yaml
- !include caseta/basement_off.yaml
- !include caseta/livingroom_pico_favorite.yaml
- !include caseta/gameroom_on.yaml
- !include caseta/gameroom_off.yaml
- !include caseta/master_bedroom_pico_on.yaml
- !include caseta/master_bedroom_pico_off.yaml
- !include caseta/master_bedroom_pico_favorite.yaml
- !include caseta/master_bedroom_on.yaml
- !include caseta/master_bedroom_off.yaml
- !include caseta/kitchen_pico_on.yaml
- !include caseta/kitchen_pico_off.yaml
- !include caseta/kitchen_on.yaml
- !include caseta/kitchen_off.yaml
- !include caseta/storage_room_b_pico_on.yaml
- !include caseta/storage_room_b_pico_off.yaml
- !include caseta/game_room_pico_on.yaml
- !include caseta/game_room_pico_off.yaml
# ToDo
# Arrive home after 11pm, turn on the front lights for 20 minutes.
