homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 363
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

# wink hub
#wink:
#  access_token: !secret wink_hub_access_token

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1

# nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#ifttt
ifttt:
  key: !secret ifttt_key

#zwave
zwave:
  usb_path: /dev/ttyUSB1

#zigbee
zha:
  usb_path: /dev/ttyUSB2
  database_path: zigbee.db

alarm_control_panel:
  - platform: manual

binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
device_tracker: !include device_trackers.yaml