homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  ## Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 351
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

#lovelace:
#  mode: yaml

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret dns_host
  server_port: 8123
  #base_url: 192.168.1.100 # todo switch back to secret and use ssl
  #server_port: 8124 # todo switch back to secret and use ssl

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google_translate

# wink hub
#wink:
#  access_token: !secret wink_hub_access_token

#mqtt:
#  broker: !secret mqtt_broker
#  port: !secret mqtt_port
#  client_id: home-assistant-1

#mqtt:
#  broker: 192.168.1.133
#  port: 9898

# nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#ifttt
ifttt:
  key: !secret ifttt_key

#lutron caseta
lutron_caseta_pro:
  bridges:
    - host: !secret caseta_hub_ip
      mac: !secret caseta_hub_mac

#zwave
zwave:
  usb_path: /dev/ttyUSB0
  device_config:
    light.front_lamp_post_level:
      polling_intensity: 1
      refresh_value: true
      delay: 1
    light.front_porch_light_level:
      polling_intensity: 1
      refresh_value: true
      delay: 1

#zigbee
zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

mobile_app:

remote:
  - platform: harmony
    name: Livingroom
    host: 192.168.1.129

emulated_roku:
  servers:
    - name: Fake Roku
      host_ip: 192.168.1.100
      listen_port: 8061
      advertise_port: 8065

alarm_control_panel:
  platform: manual
  code: !secret alarm_code
  arming_time: 10
  trigger_time: 10
  disarm_after_trigger: false

binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
device_tracker: !include device_trackers.yaml
script: !include scripts.yaml
notify: !include notifiers.yaml

input_number:
  light_step:
    name: 'Step the lights this much'
    initial: 20
    min: 1
    max: 64
    step: 50

  light_minimum:
    name: 'No dimmer than this'
    initial: 5
    min: 0
    max: 255
    step: 50

  light_maximum:
    name: 'No brighter than this'
    initial: 255
    min: 50
    max: 255
    step: 50

#snips:
#  intents:
#    LightsIntent:
#      action:
#        - service_template: >
#            {% if state == 'on' %}
#              light.turn_on
#            {% else %}
#              light.turn_off
#            {% endif %}
#          data_template:
#            entity_id: group.{{ location | replace(" ", "_") }}
