homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  ## Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 351
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml
  country: US
  external_url: !secret external_url
  internal_url: !secret internal_url

# Show links to resources in log and frontend
#introduction:
default_config:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

http:
  # reverse proxy config
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/24

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google_translate

# nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#ifttt
ifttt:
  key: !secret ifttt_key

mobile_app:

timer:

emulated_roku:
  servers:
    - name: Fake Roku
      host_ip: 192.168.1.100
      listen_port: 8061
      advertise_port: 8065

alarm_control_panel:
  platform: manual
  code: !secret alarm_code
  arming_time: 10
  trigger_time: 10
  disarm_after_trigger: false

binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
device_tracker: !include device_trackers.yaml
script: !include scripts.yaml
notify: !include notifiers.yaml

input_number:
  light_step:
    name: 'Step the lights this much'
    initial: 20
    min: 1
    max: 64
    step: 50

  light_minimum:
    name: 'No dimmer than this'
    initial: 5
    min: 0
    max: 255
    step: 50

  light_maximum:
    name: 'No brighter than this'
    initial: 255
    min: 50
    max: 255
    step: 50

conversation:

# Example configuration.yaml entry
intent_script:
  CustomOutsideHumidity:
    speech:
      text: "It is currently who knows percent humidity outside."
  CustomOutsideHumidity123:
    speech:
      text: "no idea."
  TvOff:
    action:
      service: remote.turn_off
      target:
        entity_id: remote.living_room_harmony_hub
    speech:
      text: "Thy bidding is done."
  Plex:
    action:
      service: remote.turn_on
      data:
        activity: Plex
      target:
        entity_id: remote.living_room_harmony_hub
    speech:
      text: "Thy bidding is done."
  Switch:
    action:
      service: remote.turn_on
      data:
        activity: "Play Switch"
      target:
        entity_id: remote.living_room_harmony_hub
    speech:
      text: "Thy bidding is done."

panel_iframe:
  zigbee2mqtt:
    title: "Zigbee2MQTT"
    url: "http://192.168.1.100:9442"
    icon: mdi:electrical_services
  zwave2mqtt:
    title: "Zwave2MQTT"
    url: "http://192.168.1.100:8091"
    icon: mdi:electrical_services