# - platform: mqtt
#   name: "Livingroom Chair"
#   state_topic: "wink/1/1"
#   command_topic: "wink/1/1/set"
#   brightness_state_topic: "wink/1/2"
#   brightness_command_topic: "wink/1/2/set"
#   qos: 0
#   payload_on: "ON"
#   payload_off: "OFF"
#   optimistic: false
#   retain: true
# - platform: mqtt
#   name: "Livingroom Door"
#   state_topic: "wink/2/1"
#   command_topic: "wink/2/1/set"
#   brightness_state_topic: "wink/2/2"
#   brightness_command_topic: "wink/2/2/set"
#   qos: 0
#   payload_on: "ON"
#   payload_off: "OFF"
#   optimistic: false
#   retain: true
# - platform: mqtt
#   name: "Front Lamp Post"
#   state_topic: "wink/3/1"
#   command_topic: "wink/3/1/set"
#   brightness_state_topic: "wink/3/2"
#   brightness_command_topic: "wink/3/2/set"
#   qos: 0
#   payload_on: "ON"
#   payload_off: "OFF"
#   optimistic: false
#   retain: true
# - platform: mqtt
#   name: "Front Porch"
#   state_topic: "wink/4/1"
#   command_topic: "wink/4/1/set"
#   brightness_state_topic: "wink/4/2"
#   brightness_command_topic: "wink/4/2/set"
#   qos: 0
#   payload_on: "ON"
#   payload_off: "OFF"
#   optimistic: false
#   retain: true

- platform: group
  name: Front House Lights
  entities:
    - light.front_lamp_post_level
    - light.front_porch_light_level

- platform: group
  name: Livingroom Lights
  entities:
    - light.ge_appliances_zll_light_00038784_1
    - light.living_room_floor_lamps