alias: Basement Dimmer Off
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: light.basement_light_dimmer
    from: 'on'
    to: 'off'
action:
  service: switch.turn_off
  entity_id: switch.basement_playroom_lights_switch