alias: Basement Pico On
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.basement_lights_pico
    from: '0'
    to: '1'
action:
  - service: switch.turn_on
    entity_id: switch.basement_playroom_lights_switch
  - service: light.turn_on
    entity_id: light.basement_light_dimmer