alias: Basement Dimmer On
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: light.basement_light_dimmer
    from: 'off'
    to: 'on'
action:
  service: switch.turn_on
  entity_id: switch.basement_playroom_lights_switch