alias: Game Room Dimmer On
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: light.game_room_dimmer
    from: 'off'
    to: 'on'
action:
  service: switch.turn_on
  entity_id: switch.game_room_lights_switch