alias: Game Room Pico On
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.game_room_pico
    from: '0'
    to: '1'
action:
  - service: switch.turn_on
    entity_id: switch.game_room_accent_switch