alias: Kitchen Pico Off
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.kitchen_light_pico
    from: '0'
    to: '4'
action:
  - service: switch.turn_off
    entity_id: switch.sunken_room_lights_switch
  - service: light.turn_off
    entity_id: light.kitchen_light_dimmer