alias: Kitchen Pico On
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.kitchen_light_pico
    from: '0'
    to: '1'
action:
  - service: switch.turn_on
    entity_id: switch.sunken_room_lights_switch
  - service: light.turn_on
    entity_id: light.kitchen_light_dimmer