alias: Kitchen Dimmer On
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: light.kitchen_light_dimmer
    from: 'off'
    to: 'on'
action:
  service: switch.turn_on
  entity_id: switch.sunken_room_lights_switch