alias: Livingroom Pico On
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.living_room_pico
    from: '0'
    to: '1'
action:
  service: light.turn_on
  entity_id: group.lr_light_slaves
  data:
    brightness: 255