alias: Master Bedroom Pico Off
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.master_bedroom_pico
    from: '0'
    to: '4'
action:
  - service: switch.turn_off
    entity_id: switch.master_bedroom_lights_switch
  - service: light.turn_off
    entity_id: light.master_bedroom_light_dimmer