alias: Storage Room B Pico On
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.storage_room_b_pico
    from: '0'
    to: '1'
action:
  - service: switch.turn_on
    entity_id: switch.storage_room_b_l_switch